name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Trigger only when pushed a tag like v1.0.0

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21.1.6"
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libssl-dev libpsl-dev \
          libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev \
          libxi-dev libgl1-mesa-dev libglu1-mesa-dev libasound2-dev

      - name: Configure CMake
        run: cmake --preset github

      - name: Build Project
        run: cmake --build --preset github

      - name: Create Package with CPack
        working-directory: build
        run: cpack -G ZIP

      - name: Generate Release Notes
        id: release_notes
        run: |
          echo "Release generated from tag ${{ github.ref_name }}" > body.txt

      - name: Create GitHub Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.zip
          body_path: body.txt
          name: "Malvex C2 ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}